version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      production-dependencies:
        dependency-type: production
        update-type: semver-patch
      development-dependencies:
        dependency-type: development
        update-type: semver-patch
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns: ["*"]
