name: gitleaks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  scan:
    uses: ShipFast-Syndicate/.github/.github/workflows/reusable-gitleaks.yml@v0.1.3
    with:
      config-path: .gitleaks.toml
